"""sdf

Revision ID: 852f030da96e
Revises: 
Create Date: 2024-11-14 10:55:17.935814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852f030da96e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'markets', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'markets', type_='foreignkey')
    op.drop_column('markets', 'category_id')
    # ### end Alembic commands ###
